export const Colors = {
  DIVIDER: "grey",
  LINK_TEXT: "blue",
  PRIMARY_BUTTON: "#00BFFF",
  PRIMARY_TEXT: "#000000",
  PRIMARY_TEXT_ON_MEDIA: "#FFFFFF",
  SECONDARY_TEXT: "#999999",
  SURFACE_BACKGROUND: "#FFFFFF",
  TOUCH_HIGHLIGHT: "rgba(0, 0, 0, 0.2)",
  TOUCH_HIGHLIGHT_INVERSE: "rgba(255, 255, 255, 0.2)",
  TRANSPARENT: "transparent",
};
